-- MySQL Script generated by MySQL Workbench
-- Tue May 30 07:16:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_quiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_quiz` DEFAULT CHARACTER SET utf8 ;
USE `bd_quiz` ;

-- -----------------------------------------------------
-- Table `bd_quiz`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_quiz`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `idade` INT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_quiz`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_quiz`.`contato` (
  `idcontato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idade` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `mensagem` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_quiz`.`Personalizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_quiz`.`Personalizacao` (
  `idPersonalizacao` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descrisao` VARCHAR(45) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idPersonalizacao`, `Pessoa_idPessoa`),
  INDEX `fk_Personalizacao_Pessoa1_idx` (`Pessoa_idPessoa` ASC) ,
  CONSTRAINT `fk_Personalizacao_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bd_quiz`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_quiz`.`Conquistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_quiz`.`Conquistas` (
  `idConquistas` INT NOT NULL AUTO_INCREMENT,
  `nome_conquistas` VARCHAR(45) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idConquistas`, `Pessoa_idPessoa`),
  INDEX `fk_Conquistas_Pessoa1_idx` (`Pessoa_idPessoa` ASC) ,
  CONSTRAINT `fk_Conquistas_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bd_quiz`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_quiz`.`tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_quiz`.`tema` (
  `idtema` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`idtema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_quiz`.`perguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_quiz`.`perguntas` (
  `idperguntas` INT NOT NULL AUTO_INCREMENT,
  `pergunta` TEXT NULL,
  `opcao_a` TEXT NULL,
  `opcao_b` TEXT NULL,
  `opcao_c` TEXT NULL,
  `opcao_d` TEXT NULL,
  `correta` VARCHAR(1) NULL,
  `tema_idtema` INT NOT NULL,
  PRIMARY KEY (`idperguntas`, `tema_idtema`),
  INDEX `fk_perguntas_tema1_idx` (`tema_idtema` ASC) ,
  CONSTRAINT `fk_perguntas_tema1`
    FOREIGN KEY (`tema_idtema`)
    REFERENCES `bd_quiz`.`tema` (`idtema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_quiz`.`estatisticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_quiz`.`estatisticas` (
  `idestatisticas` INT NOT NULL AUTO_INCREMENT,
  `tema_idtema` INT NOT NULL,
  `score` BIGINT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idestatisticas`, `tema_idtema`, `Pessoa_idPessoa`),
  INDEX `fk_estatisticas_tema1_idx` (`tema_idtema` ASC) ,
  INDEX `fk_estatisticas_Pessoa1_idx` (`Pessoa_idPessoa` ASC) ,
  CONSTRAINT `fk_estatisticas_tema1`
    FOREIGN KEY (`tema_idtema`)
    REFERENCES `bd_quiz`.`tema` (`idtema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estatisticas_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `bd_quiz`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
